services:
  backend:
    build: ./shocker_server
    container_name: node-backend
    expose:
      - "4000"
    restart: unless-stopped
    networks:
      - appnet

  frontend:
    build:
      context: ./shocker_gui
      args:
        VITE_OPEN_SHOCK_API_KEY: ${VITE_OPEN_SHOCK_API_KEY}
    container_name: react-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - appnet

networks:
  appnet:
    driver: bridge